[package]
name = "telegpt"
description = "A Telegram interface for GPT-3"
version = "0.1.0"
edition = "2021"
authors = ["GustavEkberg"]

[dependencies]
dotenvy = "0.15.6"
reqwest = "0.11.14"
serde_json = "1.0.93"
teloxide = "0.12.2"
tokio = { version =  "1.8", features = ["full"] }
